### ISSUE TITLE
Great shooter, no shooter.

### ISSUE THREAD

**Issue by dok441** [TimGoll/ttt2-role_mark#10]
I don't know what this is attributed to the fact that it's a shit game and 60 Tikrit not save or that it is possible to fix, the video shows how people almost 4 times the emphasis was to mark a player, but shit like that.
https://www.youtube.com/watch?v=fy_ZDOccSlA&feature=youtu.be

**Comment by TimGoll** [comment]
Keep in mind: the markergun shoots entities that need some time to travel and they have a bulletdrop. Therefore they work differently than other weapons. 

But once you marker a player he can't deal any damage to you anymore

**Comment by dok441** [comment]
I certainly understand, but on the rollers see what it's all tin, 5 times a shot was fired at people and nothing.

**Comment by TimGoll** [comment]
I just watched it on a larger screen and this confuses me. It always works for me. Maybe an addon interfers with the hit detection?

**Comment by dok441** [comment]
Perhaps it is how you use https://www.gmodstore.com/market/view/5340

**Comment by TimGoll** [comment]
I don't know, I've never used this addon. I'll ask some people on our discord
