### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dok441** [TimGoll/ttt2-role_mark#11]
[Trouble in Terrorist Town 2 (Advanced Update) - v0.5.5b] addons/ttt2-role_mark-master/lua/autorun/sh_marker_handler.lua:64: attempt to call method 'GetSubRole' (a nil value)
  1. fn - addons/ttt2-role_mark-master/lua/autorun/sh_marker_handler.lua:64
   2. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109
    3. Init - gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua:205
     4. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
      5. ScoreboardCreate - gamemodes/terrortown/gamemode/client/cl_scoreboard.lua:19
       6. UpdateScoreboard - addons/ttt2-role_mark-master/lua/autorun/sh_marker_handler.lua:76
        7. func - addons/ttt2-role_mark-master/lua/autorun/sh_marker_handler.lua:60
         8. unknown - lua/includes/extensions/net.lua:32

**Comment by Histalek** [comment]
as this error is heavily outdated and does not correspond to the current code anymore, i'm closing this issue.
