### ISSUE TITLE
Moving a translation to 1 file

### ISSUE THREAD

**Issue by dok441** [TimGoll/ttt2-role_mark#14]
You can please rewrite the code so that the entire translation of everything is in the shared file, I think many people are annoyed when something is updated and you need to flatter each time in different files to translate a small text.

**Comment by TimGoll** [comment]
You can put all your translations into one file. It shouldn't matter to you where I put my translations

**Comment by dok441** [comment]
So there is associated with the code, if I move them, then the role will break. If I knew lua, I would have done it myself, but alas. And it will be more convenient for all foreign-speaking people, not only for me.

**Comment by TimGoll** [comment]
I'm not sure if I understood your problem, but you can put your translation into `addons/my_translation/lua/autorun/client/cl_russian_translation.lua`. Add all of your LANG.Add... into an Initialize hook inside this file.

You can put there the translation of all addons no matter where the original file is located.
