### ISSUE TITLE
Round report screen spamed by marked player 

### ISSUE THREAD

**Issue by MisterClems** [TimGoll/ttt2-role_mark#30]
If a marker spam shoot a player or a marked player the event gonna be trigger every time  on the round report when the marker gonna paint him.
So the log gonna be very big at the end if someone spam shooting
![FF](https://user-images.githubusercontent.com/73431903/121439704-bf774f00-c986-11eb-9c15-aaf77cf89f82.png)
![ffff](https://user-images.githubusercontent.com/73431903/121439721-c9994d80-c986-11eb-99d9-b08e3b95dda3.png)

**Comment by TimGoll** [comment]
Oh yes, I missed that. Thanks! It also grants them way too many points!

**Comment by TimGoll** [comment]
I did not test if it works because I'm not in GMod right now. Could you please test and report back? It should work though

**Comment by MisterClems** [comment]
> I did not test if it works because I'm not in GMod right now. Could you please test and report back? It should work though

I have test and its fixed  👍

**Comment by TimGoll** [comment]
Thanks!
