### ISSUE TITLE
Marker's defi ammo incorrectly

### ISSUE THREAD

**Issue by Racpy** [TimGoll/ttt2-role_mark#33]
Marker's defi ammo factor
https://github.com/TTT-2/ttt2-role_mark/blob/bf0fd338749cfca28e4b44b4bab53764454760f6/gamemodes/terrortown/entities/weapons/weapon_ttt2_markerdefi.lua#L79

![1](https://github.com/TTT-2/ttt2-role_mark/assets/59442552/d3cebdf2-a3bf-4265-b243-a752bb04fb2e)
When the round starts, Marker's defi ammo is always only 1, if 22 players ammo should be 3.

I reselect the Marker using ULX it gives the correct amount of ammo.
![image](https://github.com/TTT-2/ttt2-role_mark/assets/59442552/14012a4d-8e81-428c-9d01-ed123fa53d85)

**Comment by TimGoll** [comment]
I reworked how the marker defi works, so this is fixed now
